system.lr: choice(1e-4, 1e-3, 1e-2)
system.recurrent_chunk_size: choice(8, 16, 32, 64, 128)
system.ppo_epochs: choice(2, 4, 8)
system.num_minibatches: choice(2, 4, 8)
system.ent_coef: choice(0.0, 1e-2, 1e-5)
system.clip_eps: choice(0.05, 0.1, 0.2)
system.max_grad_norm: choice(0.5, 5.0, 10.0)
