defaults:
  - logger: ff_isac
  - arch: anakin
  - system: ff_isac
  - env: rware
  - system/search_spaces@hydra.sweeper.params: ${system}
  - _self_
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
    sweeper:
        sampler:
            seed: 234
        direction: maximize # maximize
        study_name: mabrax-sweep
        storage: null
        n_trials: 70
        n_jobs: 1

